version: '3.9'

services:
  encurtador_url:
    image: node:16
    container_name: encurtador_url
    restart: unless-stopped
    command: bash -c "yarn install && yarn run dev"
    environment:
      # API ENVS
      - API_ID=url
      - SERVER_ENV=development
      - SERVER_PORT=3333
      # TYPEORM PATHS
      - TYPEORM_ENTITIES=./src/modules/**/database/typeorm/entities/*.ts
      - TYPEORM_MIGRATIONS=./src/shared/database/typeorm/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=./src/shared/database/typeorm/migrations
      # TYPEORM CONFIG
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_LOGGING=false
      - TYPEORM_SYNCHRONIZE=true
      # DB ADDRESS
      - TYPEORM_HOST=localhost
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=admin
      - TYPEORM_PASSWORD=admin
      - TYPEORM_DATABASE=devUrl
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/url
    working_dir: /usr/app/url