version: '3.9'

services:
  pg:
    image: postgres
    container_name: DB_POSTGRES
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=root
      - POSTGRES_DB=devUrl
    logging:
      driver: none
    ports:
      - 5432:5432
    volumes:
      - /data/PG
  
  encurtador_url:
    image: node:16
    container_name: encurtador_url
    restart: unless-stopped
    command: bash -c "npm install && npm run dev"
    environment:
      # API ENVS
      - API_ID=url
      - SERVER_ENV=development
      - SERVER_PORT=3333
      # TYPEORM PATHS
      - TYPEORM_ENTITIES=./modules/**/database/typeorm/entities/*.ts
      - TYPEORM_MIGRATIONS=./shared/database/typeorm/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=./shared/database/typeorm/migrations
      # TYPEORM CONFIG
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_LOGGING=false
      - TYPEORM_SYNCHRONIZE=false
      # DB ADDRESS
      - TYPEORM_HOST=pg
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=development
      - TYPEORM_DATABASE=url
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/url
    working_dir: /usr/app/url
    links:
      - pg
    depends_on:
      - pg  