name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: npm ci
    - name: build
      uses: icrawl/action-tsc@v1
  
  - name: AutoDeploy Request
    uses: fjogeleit/http-request-action@master
    with:
      url: 'http://yourServerIPHere:6643/nameOfApplication'
      method: 'POST'
      data: {
        "repository": "repoUrlHere",
        "first_time_commands": ["command1Here", "command2Here"],
        "commands": ["command1Here", "command2Here"]
      }